app:
  log-rotation:
    max-bytes: 1048576       
    backup-count: 3          

  alert:
    url-timeout-seconds: 10              
    telnet-timeout-seconds: 5            
    check-interval-seconds: 300          
    notification-interval-seconds: 3600  

  credentials:
    username: 'admin'  
    password: '{noop}admin'

  email:
    to: 'destinatario@dominio.com'

spring:
  mail:
    host: smtp.seuprovedor.com
    port: 587
    username: seuemail@dominio.com
    password: sua_senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  h2:
    console:
      enabled: true
      path: /h2-console
  
  datasource:
    url: jdbc:h2:mem:alertdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
